#!/usr/bin/env bash
# Export the web client and/or the dedicated server into ../build/.
# Usage: game/scripts/export.sh [web|server|all]   (needs Godot export templates)
set -euo pipefail
cd "$(dirname "$0")/.."
GODOT="${GODOT:-godot}"
target="${1:-all}"
cleanup() {
  rm -f build_info.gd build_info.gd.uid features/changelog/releases.gd features/changelog/releases.gd.uid
  rm -f features/console/repo_snapshot.gd features/console/repo_snapshot.gd.uid
  if [[ -f export_presets.cfg.orig ]]; then mv export_presets.cfg.orig export_presets.cfg; fi
}
trap cleanup EXIT
# CI sets BUILD_VERSION to the commit SHA. Clients and servers only play together when
# their versions match (see core/net/network.gd); without it the build reports "dev".
if [[ -n "${BUILD_VERSION:-}" ]]; then
  [[ "$BUILD_VERSION" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "bad BUILD_VERSION" >&2; exit 1; }
  printf '# Generated by scripts/export.sh; not committed.\nextends RefCounted\n\nconst VERSION := "%s"\n' \
    "$BUILD_VERSION" > build_info.gd
  echo "Build version: $BUILD_VERSION"
fi
# RELEASE_NOTES=1 groups the in-game changelog by release (features/changelog/); it needs
# git history and the vX.Y.Z tags. Without it the changelog is one list.
if [[ -n "${RELEASE_NOTES:-}" ]]; then
  ../scripts/release_notes.sh HEAD > features/changelog/releases.gd
  echo "Release notes: $(grep -c '"version"' features/changelog/releases.gd) releases"
fi
"$GODOT" --headless --import >/dev/null 2>&1 || true
# Bundle read-only repository metadata using Godot after its first import.
"$GODOT" --headless -s scripts/git_snapshot.gd
# Ship only the assets the game uses: the asset packs stay whole in the repo, and
# scripts/unused_assets.gd lists the rest, which is added to the presets' exclude
# filters for this export only.
unused=$("$GODOT" --headless -s scripts/unused_assets.gd 2>/dev/null | tail -n 1)
if [[ -n "$unused" ]]; then
  echo "Excluding $(tr ',' '\n' <<<"$unused" | wc -l | tr -d ' ') unused asset paths from the export"
  cp export_presets.cfg export_presets.cfg.orig
  UNUSED="$unused" awk '
    /^exclude_filter=".*"$/ { print substr($0, 1, length($0) - 1) ", " ENVIRON["UNUSED"] "\""; next }
    { print }
  ' export_presets.cfg.orig > export_presets.cfg
fi
if [[ "$target" == web || "$target" == all ]]; then
  mkdir -p ../build/web
  "$GODOT" --headless --export-release "Web" ../build/web/index.html
fi
if [[ "$target" == server || "$target" == all ]]; then
  mkdir -p ../build/server
  "$GODOT" --headless --export-release "Linux Server" ../build/server/the-game-server.x86_64
fi
