[package]
name = "gun_inspect"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot = { version = "=0.5.5", default-features = false, features = ["api-4-7", "lazy-function-tables"] }

[features]
web = ["godot/experimental-wasm", "godot/experimental-wasm-nothreads"]

[profile.release]
lto = "thin"
strip = "debuginfo"

