#!/usr/bin/env bash
# Prints a GDScript file for the in-game changelog (game/features/changelog/): the last
# COUNT releases (vX.Y.Z tags reachable from REV), newest first, and the edge (what's on
# REV since the newest release). A changelog entry belongs to the first release whose
# tagged entries.gd has its title; the oldest release in history gets every entry it has.
#   scripts/release_notes.sh [REV] [COUNT]   # defaults: HEAD 10
# REV `WORKTREE` means HEAD's releases plus the uncommitted entries.gd as the edge.
# game/scripts/export.sh writes the output to game/features/changelog/releases.gd, and
# local debug runs of the game call it directly (features/changelog/changelog.gd).
set -euo pipefail
rev="${1:-HEAD}"
count="${2:-10}"
entries=game/features/changelog/entries.gd
cd "$(dirname "$0")/.."
worktree=0
if [[ "$rev" == WORKTREE ]]; then
  worktree=1
  rev=HEAD
fi

titles() { # titles REV: the changelog titles at REV (or WORKTREE), in file order
  { if [[ "$1" == WORKTREE ]]; then cat "$entries"; else git show "$1:$entries"; fi; } 2>/dev/null |
    sed -nE 's/^[[:space:]]*"title":[[:space:]]*"(.*)",?[[:space:]]*$/\1/p' || true
}

added() { # added NEW [OLD]: titles at NEW that aren't at OLD
  if [[ -n "${2:-}" ]]; then
    grep -Fxv -f <(titles "$2") <<<"$(titles "$1")" || true
  else
    titles "$1"
  fi
}

list() { # list LINES: a GDScript array of already-escaped strings, one per line
  local out="" line
  while IFS= read -r line; do
    [[ -n "$line" ]] && out+="${out:+, }\"$line\""
  done <<<"$1"
  echo "[$out]"
}

tags=()
while IFS= read -r tag; do tags+=("$tag"); done < <(
  git tag --merged "$rev" --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n "$((count + 1))"
)

echo "# Generated by scripts/release_notes.sh during export; not committed."
echo "extends RefCounted"
echo
echo "## Entry titles added since the newest release."
edge_rev="$rev"
if ((worktree)); then edge_rev=WORKTREE; fi
echo "const EDGE: Array[String] = $(list "$(added "$edge_rev" "${tags[0]:-}")")"
echo
echo "## The last $count releases, newest first, with the entry titles each one added."
echo "const RELEASES: Array[Dictionary] = ["
for ((i = 0; i < ${#tags[@]} && i < count; i++)); do
  tag="${tags[i]}"
  printf '\t{"version": "%s", "date": "%s", "titles": %s},\n' \
    "${tag#v}" "$(git log -1 --format=%cs "$tag")" "$(list "$(added "$tag" "${tags[i + 1]:-}")")"
done
echo "]"
