#!/usr/bin/env bash
# Tests for scripts/release_notes.sh against a throwaway repository.
# Run: scripts/release_notes_test.sh
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
failures=0

# The script runs from its repo's root, wherever it's called from.
cd "$(mktemp -d)"
git init -q -b main
mkdir scripts
cp "$here/release_notes.sh" "$here/feature_notes.sh" scripts/
mkdir -p scripts/release_notes
cp "$here/release_notes/collect.gd" "$here/release_notes/project.godot" scripts/release_notes/
notes="$PWD/scripts/release_notes.sh"
git config user.email test@example.com
git config user.name test
mkdir -p game/features/changelog
entries() { # entries TITLE...: commit entries.gd with these titles, newest first
  {
    echo 'const ENTRIES: Array[Dictionary] = ['
    for title in "$@"; do
      printf '\t{\n\t\t"title": "%s",\n\t\t"summary":\n\t\t"About %s."\n\t},\n' "$title" "$title"
    done
    echo ']'
  } > game/features/changelog/entries.gd
  git add -A
  git commit -q --allow-empty -m "change"
}
check() { # check NAME WANT GOT
  if [[ "$2" != "$3" ]]; then
    printf 'FAIL: %s\n--- want\n%s\n--- got\n%s\n' "$1" "$2" "$3" >&2
    failures=$((failures + 1))
  fi
}
date="$(date +%Y-%m-%d)"

# No releases yet: everything is edge.
entries "Old"
check "no tags" "# Generated by scripts/release_notes.sh during export; not committed.
extends RefCounted

## The commit these notes are for, shortened like the HUD's.
const COMMIT := \"$(git rev-parse --short=7 HEAD)\"

## Entry titles added since the newest release.
const EDGE: Array[String] = [\"Old\"]

## The last 10 releases, newest first, with the entry titles each one added.
const RELEASES: Array[Dictionary] = [
]" "$("$notes")"

git tag v0.6.0
entries "Frogs" "Old"
entries "Say \\\"hi\\\"" "Frogs" "Old"
git tag v0.6.1
entries "Say \\\"hi\\\"" "Frogs" "Old" # a release without new entries
git tag v0.7.0
entries "Hats" "Say \\\"hi\\\"" "Frogs" "Old"

check "releases and edge" "## Entry titles added since the newest release.
const EDGE: Array[String] = [\"Hats\"]

## The last 10 releases, newest first, with the entry titles each one added.
const RELEASES: Array[Dictionary] = [
	{\"version\": \"0.7.0\", \"date\": \"$date\", \"titles\": []},
	{\"version\": \"0.6.1\", \"date\": \"$date\", \"titles\": [\"Say \\\"hi\\\"\", \"Frogs\"]},
	{\"version\": \"0.6.0\", \"date\": \"$date\", \"titles\": [\"Old\"]},
]" "$("$notes" | tail -n +7)"

check "COUNT keeps what each release added" "	{\"version\": \"0.7.0\", \"date\": \"$date\", \"titles\": []},
	{\"version\": \"0.6.1\", \"date\": \"$date\", \"titles\": [\"Say \\\"hi\\\"\", \"Frogs\"]},
]" "$("$notes" HEAD 2 | tail -n 3)"

sed -i.bak 's/^\t\t"title": "Hats",/\t\t"title": "Hats",\n\t\t"title": "Uncommitted",/' game/features/changelog/entries.gd
rm -f game/features/changelog/entries.gd.bak
check "WORKTREE adds uncommitted entries to the edge" 'const EDGE: Array[String] = ["Hats", "Uncommitted"]' \
  "$(cd / && "$notes" WORKTREE | sed -n 8p)"
check "HEAD ignores them" 'const EDGE: Array[String] = ["Hats"]' "$("$notes" | sed -n 8p)"
git checkout -q -- game/features/changelog/entries.gd

check "the commit follows REV" "const COMMIT := \"$(git rev-parse --short=7 v0.6.1)\"" \
  "$("$notes" v0.6.1 | sed -n 5p)"
check "at a release, the edge is empty" 'const EDGE: Array[String] = []' "$("$notes" v0.6.1 | sed -n 8p)"

# New files are collected alongside legacy entries. Existing release assignments survive.
mkdir -p game/features/hats/release_notes game/features/frogs/release_notes
cat > game/features/hats/release_notes/101-feathers.json <<'JSON'
{"title":"Feather hats","summary":"Hats with feathers.","notes":["Add feather hats."]}
JSON
cat > game/features/frogs/release_notes/102-colors.json <<'JSON'
{"title":"Colored frogs","summary":"Frogs in new colors.","notes":["Add colored frogs."]}
JSON
check "WORKTREE collates independent feature files" \
  'const EDGE: Array[String] = ["Colored frogs", "Feather hats", "Hats"]' \
  "$("$notes" WORKTREE | sed -n 8p)"
check "HEAD ignores untracked fragments" 'const EDGE: Array[String] = ["Hats"]' \
  "$("$notes" HEAD | sed -n 8p)"
git add game/features
git commit -q -m fragments
git tag v0.7.1
check "released fragments leave edge" 'const EDGE: Array[String] = []' \
  "$("$notes" HEAD | sed -n 8p)"
check "fragments are assigned to their first release" \
  '	{"version": "0.7.1", "date": "'"$date"'", "titles": ["Colored frogs", "Feather hats", "Hats"]},' \
  "$("$notes" HEAD | sed -n 12p)"
cat > game/features/hats/release_notes/103-ribbons.json <<'JSON'
{"title":"Ribbon hats","summary":"Hats with ribbons.","notes":["Add ribbon hats."]}
JSON
check "same feature gets a fresh note after release" 'const EDGE: Array[String] = ["Ribbon hats"]' \
  "$("$notes" WORKTREE | sed -n 8p)"
check "only unreleased fragment bullets are collected" '- Add ribbon hats.' \
  "$(scripts/feature_notes.sh edge WORKTREE)"
# A branch's fragment remains edge even if the base cut a release before it merged.
cp game/features/hats/release_notes/103-ribbons.json game/features/frogs/release_notes/104-duplicate.json
if "$notes" WORKTREE >/dev/null 2>&1; then
  echo 'FAIL: duplicate title accepted' >&2; failures=$((failures + 1))
fi
rm game/features/frogs/release_notes/104-duplicate.json
printf '%s' '{bad json' > game/features/frogs/release_notes/104-invalid.json
if "$notes" WORKTREE >/dev/null 2>&1; then
  echo 'FAIL: malformed fragment accepted' >&2; failures=$((failures + 1))
fi
rm game/features/frogs/release_notes/104-invalid.json
sed -i.bak 's/Add feather hats./Change released hats./' game/features/hats/release_notes/101-feathers.json
if scripts/feature_notes.sh validate WORKTREE >/dev/null 2>&1; then
  echo 'FAIL: released fragment mutation accepted' >&2; failures=$((failures + 1))
fi
git checkout -q -- game/features/hats/release_notes/101-feathers.json
rm game/features/hats/release_notes/101-feathers.json.bak

# Concurrent PRs to the same feature merge without a shared-list edit.
git checkout -q -b note-a
cat > game/features/hats/release_notes/200-parallel-a.json <<'JSON'
{"title":"Parallel A","summary":"First parallel change.","notes":["Add parallel A."]}
JSON
git add game/features/hats/release_notes/200-parallel-a.json
git commit -q -m note-a
git checkout -q main
git checkout -q -b note-b
cat > game/features/hats/release_notes/201-parallel-b.json <<'JSON'
{"title":"Parallel B","summary":"Second parallel change.","notes":["Add parallel B."]}
JSON
git add game/features/hats/release_notes/201-parallel-b.json
git commit -q -m note-b
git merge -q --no-edit note-a
check "parallel same-feature PRs merge and collate both notes" \
  'const EDGE: Array[String] = ["Parallel A", "Parallel B"]' \
  "$("$notes" HEAD | sed -n 8p)"

# Match the export container: the existing Godot binary and shell/Git tools only.
# This catches any attempt to bring back a separate JSON interpreter dependency.
native_bin="$(mktemp -d)"
native_godot="$(command -v "${GODOT:-godot}")"
for native_tool in bash git dirname mktemp rm cat sed grep head; do
  ln -s "$(command -v "$native_tool")" "$native_bin/$native_tool"
done
check "release collection works with no Python on PATH" "$("$notes" HEAD)" \
  "$(GODOT="$native_godot" PATH="$native_bin" "$notes" HEAD)"
rm -rf "$native_bin"

if ((failures)); then
  echo "$failures failure(s)" >&2
  exit 1
fi
echo "release_notes.sh: all tests passed"
