#!/usr/bin/env bash
# Tests for scripts/release_notes.sh against a throwaway repository.
# Run: scripts/release_notes_test.sh
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
failures=0

# The script runs from its repo's root, wherever it's called from.
cd "$(mktemp -d)"
git init -q -b main
mkdir scripts
cp "$here/release_notes.sh" scripts/
notes="$PWD/scripts/release_notes.sh"
git config user.email test@example.com
git config user.name test
mkdir -p game/features/changelog
entries() { # entries TITLE...: commit entries.gd with these titles, newest first
  {
    echo 'const ENTRIES: Array[Dictionary] = ['
    for title in "$@"; do
      printf '\t{\n\t\t"title": "%s",\n\t\t"summary":\n\t\t"About %s."\n\t},\n' "$title" "$title"
    done
    echo ']'
  } > game/features/changelog/entries.gd
  git add -A
  git commit -q --allow-empty -m "change"
}
check() { # check NAME WANT GOT
  if [[ "$2" != "$3" ]]; then
    printf 'FAIL: %s\n--- want\n%s\n--- got\n%s\n' "$1" "$2" "$3" >&2
    failures=$((failures + 1))
  fi
}
date="$(date +%Y-%m-%d)"

# No releases yet: everything is edge.
entries "Old"
check "no tags" '# Generated by scripts/release_notes.sh during export; not committed.
extends RefCounted

## Entry titles added since the newest release.
const EDGE: Array[String] = ["Old"]

## The last 10 releases, newest first, with the entry titles each one added.
const RELEASES: Array[Dictionary] = [
]' "$("$notes")"

git tag v0.6.0
entries "Frogs" "Old"
entries "Say \\\"hi\\\"" "Frogs" "Old"
git tag v0.6.1
entries "Say \\\"hi\\\"" "Frogs" "Old" # a release without new entries
git tag v0.7.0
entries "Hats" "Say \\\"hi\\\"" "Frogs" "Old"

check "releases and edge" "## Entry titles added since the newest release.
const EDGE: Array[String] = [\"Hats\"]

## The last 10 releases, newest first, with the entry titles each one added.
const RELEASES: Array[Dictionary] = [
	{\"version\": \"0.7.0\", \"date\": \"$date\", \"titles\": []},
	{\"version\": \"0.6.1\", \"date\": \"$date\", \"titles\": [\"Say \\\"hi\\\"\", \"Frogs\"]},
	{\"version\": \"0.6.0\", \"date\": \"$date\", \"titles\": [\"Old\"]},
]" "$("$notes" | tail -n +4)"

check "COUNT keeps what each release added" "	{\"version\": \"0.7.0\", \"date\": \"$date\", \"titles\": []},
	{\"version\": \"0.6.1\", \"date\": \"$date\", \"titles\": [\"Say \\\"hi\\\"\", \"Frogs\"]},
]" "$("$notes" HEAD 2 | tail -n 3)"

sed -i.bak 's/^\t\t"title": "Hats",/\t\t"title": "Hats",\n\t\t"title": "Uncommitted",/' game/features/changelog/entries.gd
rm -f game/features/changelog/entries.gd.bak
check "WORKTREE adds uncommitted entries to the edge" 'const EDGE: Array[String] = ["Hats", "Uncommitted"]' \
  "$(cd / && "$notes" WORKTREE | sed -n 5p)"
check "HEAD ignores them" 'const EDGE: Array[String] = ["Hats"]' "$("$notes" | sed -n 5p)"
git checkout -q -- game/features/changelog/entries.gd

check "at a release, the edge is empty" 'const EDGE: Array[String] = []' "$("$notes" v0.6.1 | sed -n 5p)"

if ((failures)); then
  echo "$failures failure(s)" >&2
  exit 1
fi
echo "release_notes.sh: all tests passed"
